chore(ci): fix required status checks skipped issue (#2616)

diff --git a/.github/workflows/pack-ci.yml b/.github/workflows/pack-ci.yml
--- a/.github/workflows/pack-ci.yml
+++ b/.github/workflows/pack-ci.yml
@@ -4,14 +4,14 @@ on:
   push:
     branches: ["next"]
   pull_request:
-    types: [opened, synchronize]
+    types: [opened, synchronize, reopened, edited]
 
 permissions:
   contents: read
 
 jobs:
   test:
-    if: (github.event_name == 'push' && !contains(github.event.head_commit.message, '(pm)')) || (github.event_name == 'pull_request' && !contains(github.event.pull_request.title, '(pm)'))
+    if: (github.event_name == 'push' && contains(github.event.head_commit.message, '(pack)')) || (github.event_name == 'pull_request' && contains(github.event.pull_request.title, '(pack)'))
     strategy:
       fail-fast: false
       matrix:
@@ -147,3 +147,19 @@ jobs:
         run: ${{ matrix.settings.test }}
         if: ${{ !matrix.settings.docker }}
         shell: bash
+
+  success:
+    name: utoopack-ci-success
+    runs-on: ubuntu-latest
+    if: always()
+    needs:
+      - test
+    steps:
+      - name: Check success
+        run: |
+          if [ "${{ needs.test.result }}" == "failure" ] || [ "${{ needs.test.result }}" == "cancelled" ]; then
+            echo "Tests failed or were cancelled"
+            exit 1
+          else
+            echo "Tests passed or were skipped"
+          fi
diff --git a/.github/workflows/pm-e2e.yml b/.github/workflows/pm-e2e.yml
--- a/.github/workflows/pm-e2e.yml
+++ b/.github/workflows/pm-e2e.yml
@@ -4,14 +4,14 @@ on:
   push:
     branches: ["next", "e2e-pm"]
   pull_request:
-    types: [opened, synchronize]
+    types: [opened, synchronize, reopened, edited]
 
 permissions:
   contents: read
 
 jobs:
   e2e:
-    if: (github.event_name == 'push' && !contains(github.event.head_commit.message, '(pack)')) || (github.event_name == 'pull_request' && !contains(github.event.pull_request.title, '(pack)'))
+    if: (github.event_name == 'push' && contains(github.event.head_commit.message, '(pm)')) || (github.event_name == 'pull_request' && contains(github.event.pull_request.title, '(pm)'))
     strategy:
       fail-fast: false
       matrix:
@@ -177,3 +177,19 @@ jobs:
           name: e2e-artifacts-${{ matrix.settings.target }}
           path: ${{ runner.temp }}/utoo-*
           if-no-files-found: ignore
+
+  success:
+    name: utoopm-e2e-success
+    runs-on: ubuntu-latest
+    if: always()
+    needs:
+      - e2e
+    steps:
+      - name: Check success
+        run: |
+          if [ "${{ needs.e2e.result }}" == "failure" ] || [ "${{ needs.e2e.result }}" == "cancelled" ]; then
+            echo "Tests failed or were cancelled"
+            exit 1
+          else
+            echo "Tests passed or were skipped"
+          fi
diff --git a/.github/workflows/utooweb-ci.yml b/.github/workflows/utooweb-ci.yml
--- a/.github/workflows/utooweb-ci.yml
+++ b/.github/workflows/utooweb-ci.yml
@@ -4,13 +4,14 @@ on:
   push:
     branches: ["next"]
   pull_request:
-    types: [opened, synchronize]
+    types: [opened, synchronize, reopened, edited]
 
 permissions:
   contents: read
 
 jobs:
   build:
+    if: (github.event_name == 'push' && contains(github.event.head_commit.message, '(wasm)')) || (github.event_name == 'pull_request' && contains(github.event.pull_request.title, '(wasm)'))
     name: utooweb-ci-build-wasm
     runs-on: ubuntu-latest
     steps:
@@ -44,3 +45,19 @@ jobs:
           npm run build --workspace=@utoo/pack-shared
           npm run build:local --workspace=@utoo/web
           ls packages/utoo-web/esm/utoo
+
+  success:
+    name: utooweb-ci-success
+    runs-on: ubuntu-latest
+    if: always()
+    needs:
+      - build
+    steps:
+      - name: Check success
+        run: |
+          if [ "${{ needs.build.result }}" == "failure" ] || [ "${{ needs.build.result }}" == "cancelled" ]; then
+            echo "Tests failed or were cancelled"
+            exit 1
+          else
+            echo "Tests passed or were skipped"
+          fi
