fix(ci): replace ci-success.yml with per-workflow success jobs

diff --git a/.github/workflows/pm-ci.yml b/.github/workflows/pm-ci.yml
--- a/.github/workflows/pm-ci.yml
+++ b/.github/workflows/pm-ci.yml
@@ -112,3 +112,19 @@ jobs:
         run: ${{ matrix.settings.test }}
         if: ${{ !matrix.settings.docker }}
         shell: bash
+
+  success:
+    name: utoopm-ci-success
+    runs-on: ubuntu-latest
+    if: always()
+    needs:
+      - test
+    steps:
+      - name: Check success
+        run: |
+          if [ "${{ needs.test.result }}" == "failure" ] || [ "${{ needs.test.result }}" == "cancelled" ]; then
+            echo "Tests failed or were cancelled"
+            exit 1
+          else
+            echo "Tests passed or were skipped"
+          fi
diff --git a/.github/workflows/pm-e2e.yml b/.github/workflows/pm-e2e.yml
--- a/.github/workflows/pm-e2e.yml
+++ b/.github/workflows/pm-e2e.yml
@@ -177,3 +177,19 @@ jobs:
           name: e2e-artifacts-${{ matrix.settings.target }}
           path: ${{ runner.temp }}/utoo-*
           if-no-files-found: ignore
+
+  success:
+    name: utoopm-e2e-success
+    runs-on: ubuntu-latest
+    if: always()
+    needs:
+      - e2e
+    steps:
+      - name: Check success
+        run: |
+          if [ "${{ needs.e2e.result }}" == "failure" ] || [ "${{ needs.e2e.result }}" == "cancelled" ]; then
+            echo "Tests failed or were cancelled"
+            exit 1
+          else
+            echo "Tests passed or were skipped"
+          fi
diff --git a/.github/workflows/utooweb-ci.yml b/.github/workflows/utooweb-ci.yml
--- a/.github/workflows/utooweb-ci.yml
+++ b/.github/workflows/utooweb-ci.yml
@@ -44,3 +44,19 @@ jobs:
           npm run build --workspace=@utoo/pack-shared
           npm run build:local --workspace=@utoo/web
           ls packages/utoo-web/esm/utoo
+
+  success:
+    name: utooweb-ci-success
+    runs-on: ubuntu-latest
+    if: always()
+    needs:
+      - build
+    steps:
+      - name: Check success
+        run: |
+          if [ "${{ needs.build.result }}" == "failure" ] || [ "${{ needs.build.result }}" == "cancelled" ]; then
+            echo "Tests failed or were cancelled"
+            exit 1
+          else
+            echo "Tests passed or were skipped"
+          fi
